### ISSUE TITLE
Problem when docker-compose up

### ISSUE THREAD

**Issue by KinGsNowGH** [taigaio/taiga-docker#64] opened 2021-03-18 17:04 UTC
**Describe the bug**
If i try to docker-compose up i get error as below:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Invalid top-level property "x-volumes". Valid top-level sections for this Compose file are: secrets, version, volumes, services, configs, networks, and extensions starting with "x-".

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```
I fixed just changing `docker-compose.yml`version from 3.5 to 3.4.

**To Reproduce**
git clone -b stable
docker-compose up -d

**Versions**
 - Docker version 19.03.6, build 369ce74a3c
 - docker-compose version 1.17.1, build unknown

**Comment by burtsevyg** [comment] 2021-03-22 14:09
No problem with 
```
# docker-compose -v
docker-compose version 1.28.2, build 67630359
# docker -v
Docker version 20.10.3, build 48d30b5
```

**Comment by yamila-moreno** [comment] 2021-03-29 13:01
with `version: "3.5"` in my docker-compose.yml I cannot reproduce the error. This may mean that your docker-compose version was a bit old.

I'm closing this issue, but I opened this other to update the documentation: https://github.com/taigaio/taiga-doc/issues/252

Cheers!

**Closed by yamila-moreno** 2021-03-29 13:01 UTC
