### ISSUE TITLE
Fresh container install broken

### ISSUE THREAD

**Issue by skepticalwaves** [taigaio/taiga-docker#19] opened 2021-02-02 05:11 UTC
I downloaded the repository, ran `./launch-taiga.sh`, and added an apache reverse proxy to `localhost:9000` and the instance shows this:

![image](https://user-images.githubusercontent.com/66973897/106555266-38ebc600-64eb-11eb-8202-f8de5ca1f59e.png)

**Comment by yamila-moreno** [comment] 2021-02-02 05:32
I cannot reproduce the error.

Please, open the browser dev tools and check the API requests URL.

If you go to http://localhost:9000 is it working or do you get an error?

**Comment by T-Tatsunori** [comment] 2021-02-02 07:51
In the default configuration, it can be accessed from the docker host.
If you want to access it from other clients, replace "localhost" with the IP address of the host in docker-compose.yml and docker-compose.penpot.yml.

**Comment by skepticalwaves** [comment] 2021-02-02 13:57
> I cannot reproduce the error.
Did you access the localhost:9000 with a apache reverse proxy?

The 30 minute installation includes a ngnix reverse proxy configuration at the bottom which redirects to localhost:9000:
https://resources.taiga.io/30min-setup/

Seems while this config is noted, your replies indicate it is not actually possible to expose taiga only on localhost and use a reverse proxy.

**Comment by yamila-moreno** [comment] 2021-02-02 14:08
hi there!
 
> Did you access the localhost:9000 with a apache reverse proxy?

Launching locally, you should be able to access to http://localhost:9000 without apache.
When using a reverse proxy, you have to:
- configure the reverse proxy (following the 30-minute-setup) 
- and configure the environment variables in `docker-compose.yml` with the proper domain (back and front), did you do this step?

**Comment by skepticalwaves** [comment] 2021-02-02 14:14
> Launching locally, you should be able to access to http://localhost:9000 without apache.

Yes that works.

> configure the reverse proxy (following the 30-minute-setup)
> and configure the environment variables in docker-compose.yml with the proper domain (back and front), did you do this step?

Making the following changes and attempting to use the reverse proxy does not work:

```
-  TAIGA_SITES_DOMAIN: "localhost:9000"
-  TAIGA_SITES_SCHEME: "http"
+  TAIGA_SITES_DOMAIN: "taiga.mydomain.com"
+  TAIGA_SITES_SCHEME: "https"

-      TAIGA_URL: "http://localhost:9000"
-      TAIGA_WEBSOCKETS_URL: "ws://localhost:9000"
+      TAIGA_URL: "https://taiga.mydomain.com"
+      TAIGA_WEBSOCKETS_URL: "ws://taiga.mydomain.com"
```

taiga is now available unecrypted at http://mydomain:9000 (something I did not want) and returns a blank page at http://taiga.mydomain.com (the URL I did want)

**Comment by skepticalwaves** [comment] 2021-02-02 14:16
For good measure the apache reverse config

```
<VirtualHost *:80>
    RewriteEngine On
    ProxyRequests Off
    ProxyPreserveHost On
    
    ServerName taiga.mydomain.com

    ProxyPass "/" "http://localhost:9000/" connectiontimeout=5 timeout=30 keepalive=on
    ProxyPassReverse "/" "http://localhost:9000/"

    ErrorLog ${APACHE_LOG_DIR}/taiga-error.log
    CustomLog ${APACHE_LOG_DIR}/taiga-access.log combined

    <Location "/">
        Redirect permanent "https://%{HTTP_HOST}%{REQUEST_URI}"
    </Location>


</VirtualHost>

<IfModule mod_ssl.c>
  <VirtualHost *:443>

    RewriteEngine On
    ProxyRequests Off
    ProxyPreserveHost On
    
    ServerName taiga.mydomain.com

    ProxyPass "/" "http://localhost:9000/" connectiontimeout=5 timeout=30 keepalive=on
    ProxyPassReverse "/" "http://localhost:9000/"

    ErrorLog ${APACHE_LOG_DIR}/taiga-error.log
    CustomLog ${APACHE_LOG_DIR}/taiga-access.log combined


        Include /etc/letsencrypt/options-ssl-apache.conf
        SSLCertificateFile /etc/letsencrypt/live/mydomain.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/mydomain.com/privkey.pem
  </VirtualHost>
</IfModule>

```

Copied and modified from several other reverse-proxy configs of other services which do work.

**Comment by yamila-moreno** [comment] 2021-02-02 14:18
oks! two changes should be done as far as i see:

1. in docker-compose.yml you wrote `+      TAIGA_WEBSOCKETS_URL: "ws://taiga.mydomain.com"` and it should be with `wss`
2. the apache configuration lacks a part (recently updated) with the `events` location.

```
server {
  server_name taiga.mycompany.com;

  ...

  location / {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect off;
    proxy_pass http://localhost:9000/;
  }

  # Events
  location /events {
      proxy_pass http://localhost:9000/events;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_connect_timeout 7d;
      proxy_send_timeout 7d;
      proxy_read_timeout 7d;
  }
}
```

let me know if this works!

**Comment by skepticalwaves** [comment] 2021-02-02 14:31
> in docker-compose.yml you wrote + TAIGA_WEBSOCKETS_URL: "ws://taiga.mydomain.com" and it should be with wss

This change was sufficient to fix things. Thanks.

> the apache configuration lacks a part (recently updated) with the events location.

This configuration appears to be unneeded, both in apache and nginx. The "/" redirection includes the "/events" as a subdirectory, and therefore is redundant, unless there are specific reasons for the (7 day?!) timeout for proxying?

So I have two remaining concerns
1) Why can't I do it the localhost way, like is the classic configuration for nginix-style reverse proxying.
2) The containers appear to be exposing publicly postgresql when running: `5432/tcp open  postgresql`

**Comment by yamila-moreno** [comment] 2021-02-02 14:39
> > in docker-compose.yml you wrote + TAIGA_WEBSOCKETS_URL: "ws://taiga.mydomain.com" and it should be with wss
> 
> This change was sufficient to fix things. Thanks.

great! (I'm closing the issue then)

> > the apache configuration lacks a part (recently updated) with the events location.
> 
> This configuration appears to be unneeded, both in apache and nginx. The "/" redirection includes the "/events" as a subdirectory, and therefore is redundant, unless there are specific reasons for the (7 day?!) timeout for proxying?

the main difference are the headers for the websockets

>     1. Why can't I do it the localhost way, like is the classic configuration for nginix-style reverse proxying.

Because the websockets need this configuration. We'll check on how to improve it, but for now, this is the needed configuration.

>     2. The containers appear to be exposing publicly postgresql when running: `5432/tcp open  postgresql`

they shouldn't; I'll fix it. thanks for noticing. You can remove the "ports" section under "taiga-db" service.

**Closed by yamila-moreno** 2021-02-02 14:39 UTC

**Comment by JialuZhang** [comment] 2021-02-24 20:18
In your posted configuration, the lines:
```
RewriteEngine on
```
is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine On" is introduced by Apache to explicitly enable all "RewriteRule" and "RewriteCond".

Since there is no "RewriteRule" and "RewriteCond" in the configuration, a better solution would be to delete "RewriteEngine on"

Related Apache source code snippet:

run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
