### ISSUE TITLE
Taiga front container exited

### ISSUE THREAD

**Issue by masihmoloodian** [taigaio/taiga-docker#16] opened 2021-02-01 20:15 UTC
Front container logs:

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30_config_env_subst.sh
env: can't execute 'bash': No such file or directory

**Comment by yamila-moreno** [comment] 2021-02-01 21:59
@masihmoloodian thanks for reporting! Already fixed. You need to pull again taigaio/taiga-front:latest in order to have the fixed image.

Try again and close the issue if you find it properly fixed!

Best regards,

**Comment by masihmoloodian** [comment] 2021-02-02 04:49
thanks, thats fixed.
I create superuser with` ./taiga-manage.sh createsuperuser` but in taiga login page, i cant login
Error:
According to the Taiga, your username/email or password are incorrect.

**Comment by yamila-moreno** [comment] 2021-02-02 05:36
Please, create new issues in GH for new issues.

Regarding the superuser, I cannot reproduce the behaviour.
- just in case, check that you entered the user/password correctly
- does the user exist in the db? you can run this command and check if your name appears:
```
docker exec taiga-docker_taiga-db_1 psql -U TAIGA_USER TAIGA_DB -c "select username from users_user" 
```

**Closed** 2021-02-02 05:45 UTC
