### ISSUE TITLE
[Q] Is it possible to save the history of status transitions for Kanban user stories?

### ISSUE THREAD

**Issue by k-shiratoo** [taigaio/taiga-docker#100] opened 2022-10-20 10:54 UTC
# Ideal

## 1. Move user story status

<img width="690" alt="スクリーンショット 2022-10-20 19 34 22" src="https://user-images.githubusercontent.com/93562987/196927922-eb85a9f0-7d4f-4608-892c-e8d65bc73207.png">

## 2. Unsaved activity history

<img width="1311" alt="スクリーンショット 2022-10-20 19 45 59" src="https://user-images.githubusercontent.com/93562987/196928755-6c0e2d71-b049-4e06-8990-278f03bd5f27.png">

# But this operation saves

## 1. Update userstory status
<img width="1313" alt="スクリーンショット 2022-10-20 19 49 16" src="https://user-images.githubusercontent.com/93562987/196929661-ca9d0699-b1aa-47a1-9cd0-63f739007a8f.png">

## 2. Saved activity history
<img width="1297" alt="スクリーンショット 2022-10-20 19 49 25" src="https://user-images.githubusercontent.com/93562987/196929721-b375ff15-c5c5-4fa1-b091-9720f9075d91.png">

# Question

Is it possible to add functions?

**Comment by Xaviju** [comment] 2022-10-28 08:25
Hi @k-shiratoo 
I am not able to reproduce this bug, in both cases the status change has been logged as expected.
Could you share more information on how to reproduce? Are you on taiga.io or self-hosted?

**Comment by k-shiratoo** [comment] 2022-11-01 06:21
Hi @Xaviju 
I am using self-hosted.
Is the below  image correct?
I couldn't find the source code either.

```yaml
# docker-compose.yml

version: "3.5"
services:
  taiga-front:
    image: taigaio/taiga-front:latest
```

↓ probably have the same problem.
https://github.com/kaleidos-ventures/taiga-front/issues/131

**Comment by Xaviju** [comment] 2022-11-02 06:39
OK, so let's keep a single reference of the issue. I am closing this issue, and we'll continue in the other one.

**Closed as not planned by Xaviju** 2022-11-02 06:39 UTC
Labels: duplicate, question
